name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8,17]
        a3s:
          - 1-1-23
          - 1-1-24
          - 1-1-30
          - 1-2-37
          - 1-2-38
          - 1-2-39
          - 1-2-40
          - 1-2-45
          - 1-2-46
          - 1-2-47
          - 1-2-48
          - 1-3-49
          - 1-4-53
          - 1-4-61
          - 1-4-63
          - 1-5-73
          - 1-5-75
          - 1-5-84
          - 1-7-99
          - 1-7-101
          - 1-7-103
          - 1-7-104
    steps:

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build images
        shell: pwsh
        env:
          JavaVersion: ${{ matrix.java }}
          Arma3SyncVersion: ${{ matrix.a3s }}
        run: |
          $version = $env:Arma3SyncVersion.split('-')
          $major = "$($version[0]).$($version[1])"
          $minor = "$($version[0]).$($version[1]).$($version[2])"
          docker build . --build-arg "ARMA3SYNC_VERSION=$env:Arma3SyncVersion" --build-arg "JAVA_VERSION=$env:JavaVersion" `
            -t "arwynfr/arma3sync:$minor-jre$env:JavaVersion" `
            -t "arwynfr/arma3sync:$minor"

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images
        run: docker push -a arwynfr/arma3sync
