name: publish openjdk 21 arma3sync-docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src"
      - "deps/java-21.Dockerfile"

jobs:
  build:
    uses: ./.github/workflows/publish.yaml
    with:
      java-version: 21
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
