name: publish openjdk 20 arma3sync-docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "*.sh"
      - "Dockerfile"
      - "java-20.Dockerfile"

jobs:
  build:
    uses: ./.github/workflows/publish.yaml
    with:
      java-version: 20
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
