name: publish arma3sync-docker image based on openjdk 8

on:
  workflow_dispatch:
  push:
    paths:
      - "*.sh"
      - "Dockerfile"
      - "java-8.Dockerfile"

jobs:
  build:
    uses: .github/workflows/publish.yaml@main
    with:
      java-version: 8
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
