name: publish arma3sync-docker image based on openjdk 17

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "*.sh"
      - "Dockerfile"
      - "java-17.Dockerfile"

jobs:
  build:
    uses: .github/workflows/publish.yaml@main
    with:
      java-version: 17
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
