name: publish openjdk 8 arma3sync-docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src"
      - "deps/java-8.Dockerfile"

jobs:
  build:
    uses: ./.github/workflows/publish.yaml
    with:
      java-version: 8
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
