name: publish arma3sync-docker image

on:
  workflow_call:
    inputs:
      java-version:
        description: Major java version used to build the docker image
        required: true
        type: number
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a3s-version:
          - 1-1-23
          - 1-1-24
          - 1-1-30
          - 1-2-37
          - 1-2-38
          - 1-2-39
          - 1-2-40
          - 1-2-45
          - 1-2-46
          - 1-2-47
          - 1-2-48
          - 1-3-49
          - 1-4-53
          - 1-4-61
          - 1-4-63
          - 1-5-73
          - 1-5-75
          - 1-5-84
          - 1-7-99
          - 1-7-101
          - 1-7-103
          - 1-7-104
          - 1-7-106
          - 1-7-107

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - shell: pwsh
        name: Build images
        env:
          Arma3SyncVersion: ${{ matrix.a3s-version }}
          JavaVersion: ${{ inputs.java-version }}
        run: |
          $version = $env:Arma3SyncVersion.split('-')
          $major = "$($version[0]).$($version[1])"
          $minor = "$($version[0]).$($version[1]).$($version[2])"
          docker build src `
            --build-arg "JAVA_VERSION=$env:JavaVersion" `
            --build-arg "ARMA3SYNC_VERSION=$env:Arma3SyncVersion" `
            --tag "arwynfr/arma3sync:$minor-jre$env:JavaVersion"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images
        run: docker push -a arwynfr/arma3sync
